# Generated by Django 3.0.7 on 2020-07-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_auto_20200701_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='kind',
        ),
    ]
