# Generated by Django 3.0.7 on 2020-07-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20200701_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='kind',
            new_name='category',
        ),
    ]
