# Generated by Django 3.0.8 on 2020-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_auto_20200701_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='姓名')),
                ('content', models.TextField(verbose_name='內容')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='留言日期')),
            ],
        ),
    ]
