# Generated by Django 3.0.8 on 2020-07-04 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=150)),
                ('comment_man', models.CharField(default='訪客', max_length=25)),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2020, 7, 4, 9, 43, 48, 156955, tzinfo=utc))),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Post')),
            ],
            options={
                'db_table': 'post_comment',
                'ordering': ('-comment_date',),
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
